#!/usr/bin/env python3
"""Build the research section from markdown sources.

The site has no server-side build step by design (.nojekyll, plain HTML and
CSS), so this follows the house pattern set by assets/brand/waves.py: the
generator is checked in, its output is checked in, and the output is never
hand-edited. Drop a markdown file in research/articles/, run this, commit
what it writes.

    python3 research/build.py          # pages + index + sitemap + PDFs
    python3 research/build.py --no-pdf # skip PDF generation (no Chromium)

What it writes, per article research/articles/<name>.md:

    research/<slug>/index.html   the article page
    research/<slug>/<slug>.pdf   the article as a PDF, printed from the page
    research/index.html          the index, newest first
    sitemap.xml                  research URLs replaced in place

Authoring-time dependencies (never shipped to readers):

    pip install markdown         # the only Python dependency
    Chromium                     # for PDFs; found via $CHROME or the
                                 # Playwright install, else PDFs are skipped
                                 # and article pages omit the PDF link

Front matter is a block of `key: value` lines between two `---` lines at the
top of the file. See articles/_template.md for the keys and the conventions
(root-relative asset paths, whitepapers in research/papers/).

Files whose names start with `_` are ignored; `draft: true` builds nothing
and says so. Markdown is rendered with the `extra` extension set (tables,
fenced code, footnotes) and deliberately WITHOUT `smarty`: it would turn
`--` into em-dashes, and the site's copy carries none by decision.
"""

import argparse
import functools
import html
import http.server
import os
import re
import shutil
import subprocess
import sys
import threading

try:
    import markdown
except ImportError:
    sys.exit("This generator needs the markdown package: pip install markdown")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESEARCH = os.path.join(ROOT, "research")
ARTICLES = os.path.join(RESEARCH, "articles")
SITE = "https://plicara.ai"

REQUIRED = ("title", "date", "summary")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


# --- front matter ------------------------------------------------------------

def parse_front_matter(text, name):
    """The `key: value` block between two --- lines at the top of the file."""
    if not text.startswith("---"):
        sys.exit(f"{name}: no front matter block (file must start with ---)")
    try:
        _, block, body = text.split("---", 2)
    except ValueError:
        sys.exit(f"{name}: front matter block never closes (need a second ---)")
    meta = {}
    for line in block.strip().splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if ":" not in line:
            sys.exit(f"{name}: front matter line without a colon: {line!r}")
        key, value = line.split(":", 1)
        meta[key.strip().lower()] = value.strip()
    for key in REQUIRED:
        if not meta.get(key):
            sys.exit(f"{name}: front matter is missing {key!r}")
    if not DATE_RE.match(meta["date"]):
        sys.exit(f"{name}: date must be YYYY-MM-DD, got {meta['date']!r}")
    return meta, body.lstrip("\n")


def slugify(value):
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    if not slug:
        sys.exit(f"cannot make a slug out of {value!r}")
    return slug


# --- page chrome -------------------------------------------------------------
# One copy of the header and footer for every generated page. The five
# hand-written pages carry their own copies (the accepted cost of a
# no-build-step site); everything under research/ comes from here instead,
# so at least the generated half cannot drift.

def chrome_head(title, description, canonical):
    return f"""<!DOCTYPE html>
<!-- GENERATED by research/build.py. Do not hand-edit: change the markdown
     in research/articles/ or the templates in build.py and re-run it. -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{html.escape(title)} &middot; Plicara Labs</title>
    <meta name="description" content="{html.escape(description)}" />
    <link rel="canonical" href="{canonical}" />
    <meta name="theme-color" content="#05192B" />

    <link rel="icon" href="/assets/favicon.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/assets/brand/apple-touch-icon-180.png" />

    <!-- Research reads in the warm typeset; the mono sets the nav, eyebrows
         and data. Same preload discipline as the rest of the site: hint
         exactly what renders above the fold. -->
    <link rel="preload" as="font" type="font/woff2"
          href="/assets/fonts/fraunces.woff2" crossorigin />
    <link rel="preload" as="font" type="font/woff2"
          href="/assets/fonts/newsreader.woff2" crossorigin />
    <link rel="preload" as="font" type="font/woff2"
          href="/assets/fonts/jetbrains-mono-400.woff2" crossorigin />
    <link rel="preload" as="font" type="font/woff2"
          href="/assets/fonts/jetbrains-mono-700.woff2" crossorigin />

    <link rel="stylesheet" href="/assets/tokens.css" />
    <link rel="stylesheet" href="/assets/style.css" />
  </head>
  <body>
    <a class="skip-link" href="#main">Skip to content</a>

    <header class="site-header">
      <div class="wrap">
        <a class="brand" href="/">
          <span class="brand-mark" aria-hidden="true"></span>
          Plicara Labs
        </a>
        <nav class="site-nav" aria-label="Primary">
          <a href="/#mission">Mission</a>
          <a href="/#models">Models</a>
          <a href="/#tools">Tools</a>
          <a href="/research/">Research</a>
          <a href="/benchmarks/">Benchmarks</a>
          <a href="/#principles">Principles</a>
          <a href="https://github.com/plicara">GitHub</a>
        </nav>
      </div>
    </header>
"""


CHROME_FOOT = """
    <footer class="site-footer">
      <div class="wrap">
        <span>&copy; Plicara Labs</span>
        <div class="footer-links">
          <a href="mailto:info@plicara.ai">info@plicara.ai</a>
          <a href="https://github.com/plicara">GitHub</a>
          <a href="/">Home</a>
        </div>
      </div>
    </footer>
  </body>
</html>
"""


# --- rendering ---------------------------------------------------------------

MD = markdown.Markdown(extensions=["extra"], output_format="html5")


def render_article(meta, body_md, slug, pdf_ok):
    MD.reset()
    body_html = MD.convert(body_md)
    authors = meta.get("authors", "Plicara Labs")
    pdf_link = (
        f' &middot; <a class="article-pdf-link"'
        f' href="/research/{slug}/{slug}.pdf">Download PDF</a>'
        if pdf_ok else ""
    )
    head = chrome_head(meta["title"], meta["summary"], f"{SITE}/research/{slug}/")
    return f"""{head}
    <main id="main">
      <article class="wrap article">
        <header class="article-head">
          <p class="eyebrow">research &middot; {meta["date"]}</p>
          <h1>{html.escape(meta["title"])}</h1>
          <p class="article-meta">
            {html.escape(authors)} &middot;
            <time datetime="{meta["date"]}">{meta["date"]}</time>{pdf_link}
          </p>
        </header>

        <div class="article-body">
{body_html}
        </div>

        <p class="article-back"><a href="/research/">&larr; All research</a></p>
      </article>
    </main>
{CHROME_FOOT}"""


def render_index(entries, pdf_ok):
    head = chrome_head(
        "Research",
        "Articles, analyses and whitepapers from Plicara Labs.",
        f"{SITE}/research/",
    )
    if entries:
        rows = []
        for meta, slug in entries:
            pdf = (
                f' &middot; <a class="mono" href="/research/{slug}/{slug}.pdf">pdf</a>'
                if pdf_ok else ""
            )
            rows.append(f"""        <li class="research-entry">
          <p class="research-date mono">{meta["date"]}</p>
          <div>
            <h2><a href="/research/{slug}/">{html.escape(meta["title"])}</a></h2>
            <p>{html.escape(meta["summary"])}{pdf}</p>
          </div>
        </li>""")
        listing = ('      <ul class="research-list">\n'
                   + "\n".join(rows) + "\n      </ul>")
    else:
        listing = ('      <p class="section-intro">Nothing published yet; '
                   "the first pieces are being written.</p>")
    return f"""{head}
    <main class="wrap preflight" id="main">
      <p class="eyebrow">research &middot; the notebook</p>
      <h1>Research</h1>
      <p class="lede">
        Articles and analyses from the lab, with the whitepapers behind them.
        Everything here is re-runnable where a claim depends on a number.
      </p>

{listing}
    </main>
{CHROME_FOOT}"""


# --- PDFs --------------------------------------------------------------------

def find_chromium():
    """$CHROME first, then the Playwright install, then the PATH."""
    for candidate in (os.environ.get("CHROME"), "/opt/pw-browsers/chromium",
                      shutil.which("chromium"), shutil.which("chromium-browser"),
                      shutil.which("google-chrome")):
        if candidate and os.path.exists(candidate):
            return candidate
    return None


def serve_site():
    """A throwaway HTTP server rooted at the repo, for printing.

    Printing from file:// would silently produce an unstyled PDF: the pages
    reference their stylesheets root-relatively (/assets/...), which resolves
    to the filesystem root under file:// and loads nothing. Serving the repo
    the way GitHub Pages does makes the printed page identical to the live
    one, self-hosted fonts included.
    """
    class Quiet(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *args):
            pass
    handler = functools.partial(Quiet, directory=ROOT)
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, server.server_address[1]


def print_pdf(chromium, url, pdf_path):
    """Print the article page to PDF through the print stylesheet."""
    result = subprocess.run(
        [chromium, "--headless", "--disable-gpu", "--no-sandbox",
         "--no-pdf-header-footer", "--virtual-time-budget=4000",
         f"--print-to-pdf={pdf_path}", url],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0 or not os.path.exists(pdf_path):
        sys.exit(f"PDF generation failed for {url}:\n{result.stderr[-800:]}")


# --- sitemap -----------------------------------------------------------------

def update_sitemap(slugs):
    """Replace this site's /research/ entries, leaving everything else alone.

    The match is anchored to the full site prefix: a bare "/research/"
    substring match would silently delete any future unrelated URL that
    happens to contain it (say, /blog/research-notes/methodology/).
    """
    path = os.path.join(ROOT, "sitemap.xml")
    text = open(path).read()
    text = re.sub(
        rf"[ \t]*<url>\s*<loc>{re.escape(SITE)}/research/[^<]*</loc>.*?</url>\n",
        "", text, flags=re.S)
    urls = [f"{SITE}/research/"] + [f"{SITE}/research/{s}/" for s in slugs]
    block = "".join(
        f"  <url>\n    <loc>{u}</loc>\n    <changefreq>monthly</changefreq>\n"
        f"    <priority>0.6</priority>\n  </url>\n"
        for u in urls
    )
    text = text.replace("</urlset>", block + "</urlset>")
    open(path, "w").write(text)


# --- main --------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--no-pdf", action="store_true",
                    help="skip PDFs; article pages then omit the PDF link")
    args = ap.parse_args()

    chromium = None if args.no_pdf else find_chromium()
    if not args.no_pdf and not chromium:
        print("NOTE: no Chromium found ($CHROME unset, no Playwright install);"
              " building without PDFs. Pages will omit the PDF link.")
    pdf_ok = chromium is not None
    server = port = None
    if pdf_ok:
        server, port = serve_site()

    entries = []
    seen = []
    for name in sorted(os.listdir(ARTICLES)):
        if not name.endswith(".md") or name.startswith("_"):
            continue
        path = os.path.join(ARTICLES, name)
        meta, body_md = parse_front_matter(open(path).read(), name)
        if meta.get("draft", "").lower() == "true":
            print(f"  skip  {name} (draft)")
            continue
        # An em-dash is on-brand in exactly one place: an empty table
        # cell, meaning "no comparable number" (brand.md's results-table
        # rule). Anywhere else it is prose, and the site's prose carries
        # none by decision.
        stray = [n for n, ln in enumerate(body_md.splitlines(), 1)
                 if "—" in "|".join(c for c in ln.split("|")
                                    if c.strip() != "—")]
        if stray or "—" in str(meta):
            sys.exit(f"{name}: em-dash outside an empty table cell "
                     f"(line(s) {', '.join(map(str, stray)) or 'front matter'});"
                     " write around it")
        # The override goes through slugify too: it is the one field
        # that reaches a filesystem path and an href, so it is
        # normalized to [a-z0-9-] rather than trusted.
        slug = slugify(meta.get("slug") or name[:-3])
        taken = {s: n for n, s in seen}
        if slug in taken:
            sys.exit(f"{name}: slug {slug!r} is already used by"
                     f" {taken[slug]!r}; two articles cannot share a URL")
        seen.append((name, slug))
        out_dir = os.path.join(RESEARCH, slug)
        os.makedirs(out_dir, exist_ok=True)
        out_html = os.path.join(out_dir, "index.html")
        open(out_html, "w").write(render_article(meta, body_md, slug, pdf_ok))
        if pdf_ok:
            print_pdf(chromium, f"http://127.0.0.1:{port}/research/{slug}/",
                      os.path.join(out_dir, f"{slug}.pdf"))
        entries.append((meta, slug))
        print(f"  built {name} -> research/{slug}/"
              + (f" (+ {slug}.pdf)" if pdf_ok else ""))

    if server:
        server.shutdown()

    entries.sort(key=lambda e: e[0]["date"], reverse=True)
    open(os.path.join(RESEARCH, "index.html"), "w").write(
        render_index(entries, pdf_ok))
    update_sitemap([slug for _, slug in entries])
    print(f"  built research/index.html ({len(entries)} article(s))"
          f" and refreshed sitemap.xml")

    # Stale output check: a slug directory with no matching source is most
    # likely a renamed or deleted article whose old page would keep serving.
    live = {slug for _, slug in entries}
    for name in sorted(os.listdir(RESEARCH)):
        full = os.path.join(RESEARCH, name)
        if os.path.isdir(full) and name not in ("articles", "papers") \
                and name not in live:
            print(f"  NOTE  research/{name}/ has no matching source article;"
                  " delete it if the article was renamed or removed")


if __name__ == "__main__":
    main()
